### ISSUE TITLE
iNeed: Low regard, can't give Arissa food even if hungry

### ISSUE THREAD

**Issue by chesko256** [chesko256/Arissa#41]
Because of Arissa's regard system, you can't give Arissa food if her regard is low.

**Comment by qwert44643** [comment]
I had that problem and just waited till her regard towards me was high enough and i could give her food.....i know that ineeds follower abilities has an option that you can choose"simple"i think its called that will make the follower eat when you eat and it wont consume food....i aint for sure cause i aint checked.

**Comment by chesko256** [comment]
When Arissa's regard is too low to trade with her, she will find her own apples and mead once per day.

**Comment by chesko256** [comment]
Fixed and checked in.
