### ISSUE TITLE
Open Cities compatibility

### ISSUE THREAD

**Issue by chesko256** [chesko256/Arissa#43]
Add compatibility to Arissa 2.0 compatibility framework to make compatible with Open Cities.

**Comment by qwert44643** [comment]
I'd like to see this made compatable with open cities.

**Comment by chesko256** [comment]
When Open Cities is enabled, you will not be able to ask Arissa to town roam in the following cities:
* Windhelm
* Riften
* Markarth
* Whiterun
* Solitude

The following cities are still allowed:
* Dawnstar
* Falkreath
* Morthal

This is not exactly "compatibility", but it will prevent Arissa from wandering off into the distance if the player selects this option.

**Comment by chesko256** [comment]
Fix checked in.
